name: Deploy

on:
  schedule:
    - cron: '0 12 * * 1-4' # every day 12:00 UTC Monday-Thursday

  # manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install Dependencies
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'build'